#pragma once

#include "config.h"
#include "errormsg.h"

#include <il2cpp/il2cpp_helper.h>
#include <il2cpp/il2cpp-functions.h>
#include <spdlog/spdlog.h>

#include <cstring>
#include <filesystem>
#include <fstream>
#include <vector>

// Embedded image headers (auto-generated by xmake before_build)
#include "embedded_loading_image.h"
#include "embedded_logo_image.h"
#include "embedded_cc_logo_image.h"


namespace ls_common {

struct FakeRect { float x, y, width, height; };
struct FakeVector2 { float x, y; };
struct FakeVector3 { float x, y, z; };
struct FakeColor { float r, g, b, a; };

inline void SetFullRect(void* rt, FakeVector2 aMin, FakeVector2 aMax, FakeVector2 pivot, FakeVector2 sd, FakeVector2 ap)
{
  if (!rt) return;
  static auto rt_h  = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "RectTransform");
  static auto fn_am = rt_h.GetInvokeMethod<void, FakeVector2>("set_anchorMin");
  static auto fn_ax = rt_h.GetInvokeMethod<void, FakeVector2>("set_anchorMax");
  static auto fn_pv = rt_h.GetInvokeMethod<void, FakeVector2>("set_pivot");
  static auto fn_sd = rt_h.GetInvokeMethod<void, FakeVector2>("set_sizeDelta");
  static auto fn_ap = rt_h.GetInvokeMethod<void, FakeVector2>("set_anchoredPosition");
  if (!fn_am || !fn_ax || !fn_pv || !fn_sd || !fn_ap) return;
  fn_am.Invoke(rt, aMin);
  fn_ax.Invoke(rt, aMax);
  fn_pv.Invoke(rt, pivot);
  fn_sd.Invoke(rt, sd);
  fn_ap.Invoke(rt, ap);
}

inline void* CreateSpriteFromTexture(void* tex, int32_t width, int32_t height)
{
  if (!tex || width <= 0 || height <= 0) return nullptr;
  static auto spr_h  = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "Sprite");
  static auto fn_cre = spr_h.GetInvokeMethod<void*, void*, FakeRect, FakeVector2>("Create");
  if (!fn_cre) return nullptr;
  FakeRect    rect{0.0f, 0.0f, static_cast<float>(width), static_cast<float>(height)};
  FakeVector2 pivot{0.5f, 0.5f};
  return fn_cre.Invoke(nullptr, tex, rect, pivot);
}

inline bool ConfigureImageSprite(void* imgComp, void* spr, bool preserveAspect)
{
  if (!imgComp || !spr) return false;
  static auto img_h  = il2cpp_get_class_helper("UnityEngine.UI", "UnityEngine.UI", "Image");
  static auto fn_spr = img_h.GetInvokeMethod<void, void*>("set_sprite");
  static auto fn_col = img_h.GetInvokeMethod<void, FakeColor>("set_color");
  static auto fn_typ = img_h.GetInvokeMethod<void, int32_t>("set_type");
  static auto fn_asp = img_h.GetInvokeMethod<void, bool>("set_preserveAspect");
  static auto fn_ray = img_h.GetInvokeMethod<void, bool>("set_raycastTarget");
  if (!fn_spr || !fn_col || !fn_typ || !fn_asp) return false;

  bool      ok = fn_spr.Invoke(imgComp, spr);
  FakeColor white{1.0f, 1.0f, 1.0f, 1.0f};
  ok &= fn_col.Invoke(imgComp, white);
  ok &= fn_typ.Invoke(imgComp, int32_t{0});
  ok &= fn_asp.Invoke(imgComp, preserveAspect);
  if (fn_ray) {
    ok &= fn_ray.Invoke(imgComp, false);
  }
  return ok;
}

inline void HideImage(void* imgComp)
{
  if (!imgComp) return;
  static auto img_h  = il2cpp_get_class_helper("UnityEngine.UI", "UnityEngine.UI", "Image");
  static auto fn_col = img_h.GetInvokeMethod<void, FakeColor>("set_color");
  FakeColor   clear{0.0f, 0.0f, 0.0f, 0.0f};
  fn_col.Invoke(imgComp, clear);
}

inline void SafeDestroy(void* obj)
{
  if (!obj) return;
  try {
    static auto obj_h      = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "Object");
    static auto fn_destroy = obj_h.GetInvokeMethod<void, void*>("Destroy");
    if (fn_destroy) fn_destroy.Invoke(nullptr, obj);
  } catch (...) {}
}

inline void ReadIl2CppString(void* strObj, char* buf, int bufSize)
{
  buf[0] = '\0';
  if (!strObj || bufSize <= 1) return;
  const auto* chars = reinterpret_cast<const char16_t*>((ptrdiff_t)strObj + 0x14);
  int         i     = 0;
  for (; i < bufSize - 1 && chars[i]; ++i)
    buf[i] = static_cast<char>(chars[i]);
  buf[i] = '\0';
}

inline void* FindRootCanvas(void* parentTransform)
{
  static auto go_h     = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "GameObject");
  static auto tr_h     = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "Transform");
  static auto canvas_h = il2cpp_get_class_helper("UnityEngine.UIModule", "UnityEngine", "Canvas");
  static auto fn_get_parent = tr_h.GetMethod("get_parent");
  static auto fn_get_go     = tr_h.GetMethod("get_gameObject");
  static auto fn_gc_go      = go_h.GetMethod("GetComponent", 1);
  void*       canvasType    = canvas_h.GetType();

  void* cur = parentTransform;
  while (cur) {
    void* curGO = fn_get_go ? reinterpret_cast<void* (*)(void*)>(fn_get_go)(cur) : nullptr;
    if (curGO && fn_gc_go && canvasType) {
      if (reinterpret_cast<void* (*)(void*, void*)>(fn_gc_go)(curGO, canvasType))
        return cur;
    }
    cur = fn_get_parent ? reinterpret_cast<void* (*)(void*)>(fn_get_parent)(cur) : nullptr;
  }
  return parentTransform;
}

inline Il2CppGCHandle LoadTextureFromBytes(const uint8_t* data, size_t size)
{
  if (!data || size == 0) return nullptr;
  static auto tex_h   = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "Texture2D");
  static auto conv_h  = il2cpp_get_class_helper("UnityEngine.ImageConversionModule", "UnityEngine", "ImageConversion");
  static auto fn_load = conv_h.GetInvokeMethodSpecial<bool, void*, void*, bool>(
      "LoadImage", [](int param_count, const Il2CppType** param) {
        return param_count == 3 && param[1]->type == IL2CPP_TYPE_SZARRAY && param[2]->type == IL2CPP_TYPE_BOOLEAN;
      });
  if (!tex_h.isValidHelper() || !fn_load) return nullptr;

  static auto  byte_h = il2cpp_get_class_helper("mscorlib", "System", "Byte");
  Il2CppArray* arr    = il2cpp_array_new(byte_h.get_cls(), size);
  if (!arr) return nullptr;
  std::memcpy(((Il2CppArraySize*)arr)->vector, data, size);

  auto* tex = il2cpp_object_new(tex_h.get_cls());
  if (!tex) return nullptr;

  // Root both managed objects before invoking Unity; native local pointers are
  // not sufficient roots if an invocation triggers a collection.
  Il2CppGCHandle bytes_handle   = il2cpp_gchandle_new(reinterpret_cast<Il2CppObject*>(arr), false);
  Il2CppGCHandle texture_handle = il2cpp_gchandle_new(tex, false);
  if (!bytes_handle || !texture_handle) {
    if (bytes_handle) il2cpp_gchandle_free(bytes_handle);
    if (texture_handle) il2cpp_gchandle_free(texture_handle);
    return nullptr;
  }

  static auto ctor = tex_h.GetInvokeMethodSpecial<void, int32_t, int32_t, int32_t, bool>(
      ".ctor", [](int param_count, const Il2CppType** param) {
        return param_count == 4 && param[3]->type == IL2CPP_TYPE_BOOLEAN;
      });
  if (ctor) {
    int32_t width = 2, height = 2, textureFormat = 4;
    bool    mipChain    = false;
    if (!ctor.Invoke(il2cpp_gchandle_get_target(texture_handle), width, height, textureFormat, mipChain)) {
      il2cpp_gchandle_free(bytes_handle);
      il2cpp_gchandle_free(texture_handle);
      return nullptr;
    }
  }

  const bool loaded = fn_load.Invoke(nullptr, il2cpp_gchandle_get_target(texture_handle),
                                     il2cpp_gchandle_get_target(bytes_handle), false);
  il2cpp_gchandle_free(bytes_handle);
  if (!loaded) {
    il2cpp_gchandle_free(texture_handle);
    return nullptr;
  }
  return texture_handle;
}

// --- Texture management (shared state) ---

inline uint32_t ReadBigEndian32(const uint8_t* value)
{
  return (static_cast<uint32_t>(value[0]) << 24) | (static_cast<uint32_t>(value[1]) << 16)
         | (static_cast<uint32_t>(value[2]) << 8) | static_cast<uint32_t>(value[3]);
}

inline bool ReadPngDimensions(const uint8_t* data, size_t size, int32_t& width, int32_t& height)
{
  static constexpr uint8_t png_signature[] = {0x89, 'P', 'N', 'G', 0x0D, 0x0A, 0x1A, 0x0A};
  if (!data || size < 24 || std::memcmp(data, png_signature, sizeof(png_signature)) != 0
      || std::memcmp(data + 12, "IHDR", 4) != 0) {
    return false;
  }

  const auto parsed_width  = ReadBigEndian32(data + 16);
  const auto parsed_height = ReadBigEndian32(data + 20);
  if (parsed_width == 0 || parsed_height == 0 || parsed_width > INT32_MAX || parsed_height > INT32_MAX) {
    return false;
  }

  width  = static_cast<int32_t>(parsed_width);
  height = static_cast<int32_t>(parsed_height);
  return true;
}

// Loading assets live for one LoginSequence generation. Strong handles keep
// the managed wrappers reachable while that generation is active; the next
// LoginSequence releases them and creates fresh Unity native resources.
class RootedImageAsset final
{
public:
  [[nodiscard]] bool Load(const uint8_t* data, size_t size, int32_t fallback_width, int32_t fallback_height,
                          const char* name)
  {
    if (Texture()) return true;

    width_  = fallback_width;
    height_ = fallback_height;
    if (!ReadPngDimensions(data, size, width_, height_)) {
      spdlog::warn("[LS] {} is not a supported PNG; using fallback dimensions {}x{}", name, width_, height_);
    }

    texture_handle_ = LoadTextureFromBytes(data, size);
    if (!texture_handle_) {
      spdlog::warn("[LS] failed to load and root {} texture", name);
      return false;
    }
    name_ = name;
    spdlog::debug("[LS] loaded and rooted {} texture ({}x{})", name_, width_, height_);
    return true;
  }

  [[nodiscard]] void* Texture() const
  {
    return texture_handle_ ? il2cpp_gchandle_get_target(texture_handle_) : nullptr;
  }

  [[nodiscard]] void* Sprite()
  {
    if (sprite_handle_) return il2cpp_gchandle_get_target(sprite_handle_);

    void* texture = Texture();
    if (!texture) return nullptr;
    auto* sprite = reinterpret_cast<Il2CppObject*>(CreateSpriteFromTexture(texture, width_, height_));
    if (!sprite) {
      spdlog::warn("[LS] failed to create {} sprite", name_);
      return nullptr;
    }

    sprite_handle_ = il2cpp_gchandle_new(sprite, false);
    if (!sprite_handle_) spdlog::warn("[LS] failed to root {} sprite", name_);
    return sprite_handle_ ? il2cpp_gchandle_get_target(sprite_handle_) : nullptr;
  }

  void Reset()
  {
    if (sprite_handle_) {
      il2cpp_gchandle_free(sprite_handle_);
      sprite_handle_ = nullptr;
    }
    if (texture_handle_) {
      il2cpp_gchandle_free(texture_handle_);
      texture_handle_ = nullptr;
    }
    width_  = 0;
    height_ = 0;
    name_   = "loading asset";
  }

  [[nodiscard]] int32_t Width() const { return width_; }
  [[nodiscard]] int32_t Height() const { return height_; }

private:
  Il2CppGCHandle texture_handle_ = nullptr;
  Il2CppGCHandle sprite_handle_  = nullptr;
  int32_t        width_          = 0;
  int32_t        height_         = 0;
  const char*    name_           = "loading asset";
};

inline RootedImageAsset& LoadingAsset()
{
  static RootedImageAsset asset;
  return asset;
}

inline RootedImageAsset& LogoAsset()
{
  static RootedImageAsset asset;
  return asset;
}

inline RootedImageAsset& CCLogoAsset()
{
  static RootedImageAsset asset;
  return asset;
}

inline void ResetLoadingAssetsForScene()
{
  LoadingAsset().Reset();
  LogoAsset().Reset();
  CCLogoAsset().Reset();
  spdlog::debug("[LS] released previous loading assets for new LoginSequence");
}

inline RootedImageAsset* GetLoadingAsset()
{
  auto& asset = LoadingAsset();
  if (asset.Texture()) return &asset;

  const std::string& path = Config::Get().loader_image;
  if (!path.empty() && std::filesystem::exists(path)) {
    std::ifstream f(path, std::ios::binary);
    if (f.is_open()) {
      std::vector<uint8_t> data(std::istreambuf_iterator<char>(f), {});
      if (!data.empty() && asset.Load(data.data(), data.size(), 1334, 750, "custom loading background")) {
        return &asset;
      }
    }
  }

  return asset.Load(g_embeddedLoadingImage, g_embeddedLoadingImage_SIZE, 1334, 750, "embedded loading background")
             ? &asset
             : nullptr;
}

inline RootedImageAsset* GetLogoAsset()
{
  auto& asset = LogoAsset();
  return (asset.Texture() || asset.Load(g_embeddedLogoImage, g_embeddedLogoImage_SIZE, 600, 828, "mod logo"))
             ? &asset
             : nullptr;
}

inline RootedImageAsset* GetCCLogoAsset()
{
  auto& asset = CCLogoAsset();
  return (asset.Texture()
          || asset.Load(g_embeddedCCLogoImage, g_embeddedCCLogoImage_SIZE, 600, 815, "community logo"))
             ? &asset
             : nullptr;
}

inline void* CreateImageOverlay(const char* name, RootedImageAsset& asset, void* parentTransform, FakeVector2 aMin,
                                FakeVector2 aMax, FakeVector2 pivot, FakeVector2 sd, FakeVector2 ap,
                                bool preserveAspect, bool placeAsFirstSibling)
{
  if (!parentTransform) return nullptr;

  static auto go_h  = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "GameObject");
  static auto rt_h  = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "RectTransform");
  static auto tr_h  = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "Transform");
  static auto img_h = il2cpp_get_class_helper("UnityEngine.UI", "UnityEngine.UI", "Image");

  static auto fn_go_ctor = go_h.GetInvokeMethodSpecial<void, void*>(".ctor", [](int n, const Il2CppType** p) {
    return n == 1 && p[0]->type == IL2CPP_TYPE_STRING;
  });
  static auto fn_get_tr  = go_h.GetInvokeMethod<void*>("get_transform");
  static auto fn_setpar  = tr_h.GetInvokeMethodSpecial<void, void*, bool>(
      "SetParent", [](int n, const Il2CppType**) { return n == 2; });
  static auto fn_setfst  = tr_h.GetInvokeMethod<void>("SetAsFirstSibling");
  static auto fn_addcomp = go_h.GetInvokeMethod<void*, void*>("AddComponent");
  static auto fn_gc      = go_h.GetInvokeMethod<void*, void*>("GetComponent");
  if (!fn_go_ctor || !fn_get_tr || !fn_setpar || !fn_addcomp || !fn_gc) return nullptr;

  void* spr = asset.Sprite();
  if (!spr) return nullptr;

  auto* go = il2cpp_object_new(go_h.get_cls());
  if (!go) return nullptr;
  Il2CppGCHandle go_handle = il2cpp_gchandle_new(go, false);
  if (!go_handle) return nullptr;

  void* nameStr = il2cpp_string_new(name);
  if (!fn_go_ctor.Invoke(go, nameStr)) {
    il2cpp_gchandle_free(go_handle);
    return nullptr;
  }

  void* tr = fn_get_tr.Invoke(go);
  if (!tr) {
    il2cpp_gchandle_free(go_handle);
    return nullptr;
  }
  void* rootCanvas = FindRootCanvas(parentTransform);
  if (!rootCanvas || !fn_setpar.Invoke(tr, rootCanvas, false)) {
    il2cpp_gchandle_free(go_handle);
    return nullptr;
  }
  if (placeAsFirstSibling && fn_setfst) fn_setfst.Invoke(tr);

  void* imgType   = img_h.GetType();
  if (!imgType) {
    il2cpp_gchandle_free(go_handle);
    return nullptr;
  }
  void* imgComp = fn_addcomp.Invoke(go, imgType);
  if (!imgComp) {
    il2cpp_gchandle_free(go_handle);
    return nullptr;
  }

  void* rtType    = rt_h.GetType();
  if (!rtType) {
    il2cpp_gchandle_free(go_handle);
    return nullptr;
  }
  void* rt = fn_gc.Invoke(go, rtType);
  if (!rt) {
    il2cpp_gchandle_free(go_handle);
    return nullptr;
  }
  SetFullRect(rt, aMin, aMax, pivot, sd, ap);

  if (!ConfigureImageSprite(imgComp, spr, preserveAspect)) {
    il2cpp_gchandle_free(go_handle);
    return nullptr;
  }

  void* result = il2cpp_gchandle_get_target(go_handle);
  il2cpp_gchandle_free(go_handle);
  spdlog::debug("[LS] created {} overlay", name);
  return result;
}

inline void CreateLogoOverlayEx(const char* name, RootedImageAsset* asset, void* parentTransform, void*& outGO,
                                float xSide)
{
  if (outGO) return;
  try {
    if (!asset || !parentTransform) return;

    constexpr float kRefScreenWidth = 1920.0f;
    constexpr float kRefLogoWidth   = 150.0f;
    constexpr float kRefPadX        = 30.0f;
    constexpr float kRefPadY        = 185.0f;

    static auto screen_h = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "Screen");
    static auto fn_sw    = screen_h.GetInvokeMethod<int32_t>("get_width");
    static auto fn_sh    = screen_h.GetInvokeMethod<int32_t>("get_height");
    float       sw       = static_cast<float>(fn_sw.Invoke(nullptr));
    float       sh       = static_cast<float>(fn_sh.Invoke(nullptr));
    if (sw <= 0.0f) sw = 1334.0f;
    if (sh <= 0.0f) sh = 750.0f;

    float scale = (sw / kRefScreenWidth) * Config::Get().loader_logo_scale;

    const int32_t lw = asset->Width();
    const int32_t lh = asset->Height();
    float logoWidth = kRefLogoWidth * scale;
    float logoPixH  = logoWidth * ((lw > 0) ? (float)lh / (float)lw : 1.0f);
    float padX      = kRefPadX * scale;
    float padY      = kRefPadY * scale;

    FakeVector2 aMin, aMax;
    if (xSide < 0.0f) {
      aMin = {padX / sw, padY / sh};
      aMax = {(padX + logoWidth) / sw, (padY + logoPixH) / sh};
    } else {
      aMin = {(sw - padX - logoWidth) / sw, padY / sh};
      aMax = {(sw - padX) / sw, (padY + logoPixH) / sh};
    }

    outGO = CreateImageOverlay(name, *asset, parentTransform, aMin, aMax,
                               {0.5f, 0.5f}, {0.0f, 0.0f}, {0.0f, 0.0f},
                               true, false);
  } catch (...) {}
}

inline void CreateLogoOverlay(void* parentTransform, void*& logoGO)
{
  CreateLogoOverlayEx("STFCModLogo", GetLogoAsset(), parentTransform, logoGO, 1.0f);
}

inline void CreateCCLogoOverlay(void* parentTransform, void*& ccLogoGO)
{
  CreateLogoOverlayEx("STFCCCLogo", GetCCLogoAsset(), parentTransform, ccLogoGO, -1.0f);
}

inline void ApplySpriteToImage(void* imageComp, RootedImageAsset& asset)
{
  if (!imageComp) return;
  void* spr = asset.Sprite();
  if (!spr) return;
  static auto img_h  = il2cpp_get_class_helper("UnityEngine.UI", "UnityEngine.UI", "Image");
  static auto fn_ovr = img_h.GetInvokeMethod<void, void*>("set_overrideSprite");
  static auto fn_drt = img_h.GetInvokeMethod<void>("SetVerticesDirty");
  fn_ovr.Invoke(imageComp, spr);
  if (!ConfigureImageSprite(imageComp, spr, false)) return;
  fn_drt.Invoke(imageComp);
}

inline void* CreateBGOverlay(void* parentTransform, RootedImageAsset& asset)
{
  return CreateImageOverlay("STFCModBG", asset, parentTransform,
                            {0.0f, 0.0f}, {1.0f, 1.0f}, {0.5f, 0.5f},
                            {0.0f, 0.0f}, {0.0f, 0.0f}, false,
                            true);
}

} // namespace ls_common
